services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PG_DATABASE} -U ${PG_USER}"]
      interval: 5s
      retries: 3

  otreeserver:
    build: .
    command: otree prodserver
    ports:
      - "${OTREE_PORT}:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DATABASE}"
      OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
      OTREE_PRODUCTION: ${OTREE_PRODUCTION}
      OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
      PORT: 8000
    volumes:
      - .:/app

volumes:
  postgres_data:
